name: module_calculadora
description: "Módulo de Nettia: calculadoras de red (subred IPv4, dividir en subredes, VLSM, IPv6)."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  nettia_core:
    path: ../nettia_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
